#!/usr/bin/env python3
"""PH governance: constitution materialization, navigation refresh, content evidence.

Since 1.2.3 these generic capabilities live here instead of the retired
spec-kit integration script. The constitution is a project document:

- ``materialize-constitution`` creates ``.agents/project-harness/constitution.md``
  when it is missing (a fresh install). An existing constitution is user-owned
  content and is never overwritten.
- ``refresh-navigation`` replaces only the managed navigation entries inside
  the marker-guarded zone (``## 约束导航``). Principles, commentary and any
  later sections stay byte-identical. The caller must have reviewed the file
  and pass its sha256 as ``--expected-sha``; a file that changed since the
  review is refused.
- ``verify-content`` checks the project-specific constraints tree and its
  evidence report (the checks live in ``ph_layout.verify_constraints``).
- ``verify`` is a read-only integrity check of the materialized constitution:
  the PH marker zone is present, the navigation covers exactly the live
  constraints documents, and every entry carries a usable reading moment.

No third-party dependencies; no network access.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

# Script-entry guard, same regression class as ph_init.py: run as a CLI in
# an installed repository, the kernel imports below must not leave
# __pycache__ next to the scripts during a read-only check. Importing this
# module as a library keeps no side effect.
if __name__ == "__main__":
    sys.dont_write_bytecode = True

import ph_init
import ph_layout

HOME = ph_layout.HOME
CONSTITUTION = ph_layout.CONSTITUTION
CONSTRAINTS = ph_layout.CONSTRAINTS

# Legacy marker written by the retired spec-kit integration script; kept as a
# recognized zone anchor so constitutions materialized before 1.2.3 keep
# refreshing in place.
LEGACY_MARKER = (
    "<!-- PH-managed constitution override: generated by ph_speckit.py; "
    "regenerate with `ph_speckit.py constitution --repo <repo> --apply`. -->"
)
# 1.2.3+ marker.
GOVERNANCE_MARKER = (
    "<!-- PH-managed constitution navigation: generated by ph_governance.py; "
    "refresh with `ph_governance.py refresh-navigation --repo <repo> --apply`. -->"
)
MARKERS = (GOVERNANCE_MARKER, LEGACY_MARKER)
NAV_HEADING = "## 约束导航"
EMPTY_NAVIGATION = "（constraints/ 目前没有可引用的正文文档；初始化补全后刷新本导航。）"
ENTRY_PATTERN = r"^- \[[^\]]+\]\([^)]+\)\n  使用时机：[^\n]*(?:\n|$)"
USAGE_PATTERN = r"^(?:适用|使用时机|when)[：:]\s*(.+)$"
UPSTREAM_PLACEHOLDERS = ("[PROJECT_NAME]", "[PRINCIPLE_")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
# Pre-1.2.1 root layout that must stay retired; a live copy would shadow the
# relocated runtime and specs trees.
LEGACY_ROOTS = (".specify", "specs")


class PHGovernanceError(Exception):
    """User-facing failure that becomes a non-zero exit, not a traceback."""


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def find_repo(explicit: str) -> Path:
    """Resolve the repository root that carries the canonical manifest."""

    start = Path(explicit).resolve()
    if not start.exists():
        raise PHGovernanceError(f"repository path does not exist: {start}")
    cur = start
    while True:
        if (cur / ".agents" / "ph.json").is_file():
            return cur
        nxt = cur.parent
        if nxt == cur:
            raise PHGovernanceError(f"no Project Harness manifest found above {start}")
        cur = nxt


def _real_dir(repo: Path, rel: str) -> Path:
    try:
        return ph_layout.real_directory(repo, rel)
    except ValueError as exc:
        raise PHGovernanceError(str(exc)) from exc


def _safe_dest(repo: Path, rel: str) -> Path:
    """A repository-local regular-file destination without links in ancestors.

    In-place writes (``write_text`` / ``write_bytes``) go through the existing
    inode, so a hardlinked destination would silently write through to the
    linked file outside the repository, and a junctioned ancestor would
    redirect the whole path. Both shapes are refused before any caller writes.
    """

    dest = (repo / rel).absolute()
    if dest.is_symlink() or ph_init.is_disallowed_reparse(dest):
        raise PHGovernanceError(f"{rel} is a symlink or junction; refusing to write")
    if dest.exists() and not dest.is_file():
        raise PHGovernanceError(f"{rel} is not a regular file")
    if dest.is_file() and dest.stat().st_nlink > 1:
        raise PHGovernanceError(f"{rel} is a hardlink; refusing to write")
    cur = repo.absolute()
    for part in Path(rel).parts[:-1]:
        cur = cur / part
        if cur.is_symlink() or ph_init.is_disallowed_reparse(cur) or (cur.exists() and not cur.is_dir()):
            raise PHGovernanceError(f"{rel}: {cur} is not a real repository-local directory")
    return dest


def extract_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip() or fallback
    return fallback


def extract_readme_description(readme: Path, doc_rel: str) -> str | None:
    if not readme.is_file() or readme.is_symlink():
        return None
    text = readme.read_text(encoding="utf-8", errors="replace")
    heading = "**" + doc_rel.split("/")[-1] + "**"
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.strip() == heading:
            for candidate in lines[index + 1:]:
                if candidate.strip():
                    return candidate.strip().lstrip("-").strip() or None
    for line in lines:
        if line.startswith("- ") and doc_rel.split("/")[-1] in line:
            desc = line[2:].split("：", 1)[-1].split(":", 1)[-1]
            if desc.strip():
                return desc.strip()
    return None


def navigation_rows(repo: Path, *, strict_usage: bool) -> list[str]:
    """One navigation row per live constraints document (directories included).

    strict_usage is the reviewed-refresh mode: an entry without a verified
    reading moment (or still marked 待确认) stops the refresh instead of
    publishing a guess. Materialization is the lenient mode: unrecognized
    entries publish the explicit 待确认 wording so the gap is visible.
    """

    governance_root = _real_dir(repo, CONSTRAINTS)
    rows: list[str] = []
    for path in ph_layout.constraint_entries(repo):
        relative_in_home = path.relative_to(repo / HOME).as_posix()
        relative_in_constraints = path.relative_to(governance_root).as_posix()
        if path.is_dir():
            title, usage = path.name, ph_layout.RECORD_DIRECTORIES[relative_in_constraints]
        else:
            rel = path.relative_to(repo).as_posix()
            _safe_dest(repo, rel)
            body = path.read_text(encoding="utf-8", errors="replace")
            title = extract_title(body, path.name)
            match = re.search(USAGE_PATTERN, body, re.MULTILINE)
            if match:
                usage = match.group(1).strip()
            elif strict_usage:
                raise PHGovernanceError(f"missing usage: {relative_in_constraints}")
            else:
                usage = ph_layout.RECORD_DIRECTORIES.get(relative_in_constraints)
            if usage is None:
                for candidate in (path.parent / "README.md", path.parent.parent / "README.md"):
                    usage = extract_readme_description(candidate, relative_in_constraints)
                    if usage:
                        break
            if usage is None:
                if strict_usage:
                    raise PHGovernanceError(f"missing usage: {relative_in_constraints}")
                usage = "待确认：本篇的适用范围与阅读时机未能从目录索引或正文识别，请补充后再依赖。"
        state = ""
        if path.is_file():
            body = path.read_text(encoding="utf-8", errors="replace")
            if "<填写：" in body or "<填写:" in body:
                state = "（骨架：占位符未填写，初始化补全后生效）"
        rows.append(f"- [{title}]({relative_in_home})\n  使用时机：{usage}{state}")
    return rows


def render_constitution(repo: Path, *, strict_usage: bool) -> bytes:
    rows = navigation_rows(repo, strict_usage=strict_usage)
    navigation = "\n".join(rows) if rows else EMPTY_NAVIGATION
    zone = (
        f"\n{GOVERNANCE_MARKER}\n"
        f"{NAV_HEADING}\n\n"
        "以下文档是本仓库现行约束的唯一正文，本导航只做逐篇引用、不复制正文；"
        "阅读时机与适用范围以各篇正文及其目录索引为准，冲突时以正文为准。维护规则：新增、移动或删除"
        f" {CONSTRAINTS} 下的文档后，由 PH init / 升级流程刷新本区。\n\n"
        f"{navigation}\n"
    )
    body = (
        f"# {repo.name} 项目宪法\n\n"
        "## 约束来源\n\n"
        "本项目现行约束保存在 constraints/。开始工作前，按下方使用条件读取相关文件正文，"
        "并将适用规则用于需求、设计、实现和验收。导航不是正文的替代品。\n\n"
        "## 维护要求\n\n"
        "修改原则或约束必须保留项目既有决定；发现冲突时先核实，不静默放宽规则。"
        "记忆及 archive 中的历史资料仅供追溯，不作为当前授权或现行规则。\n"
    )
    return (body + zone).encode("utf-8")


def materialize_constitution(repo: Path, apply: bool) -> dict:
    """Create the materialized constitution only when it is missing."""

    _real_dir(repo, HOME)
    item = {"action": "materialize-constitution", "apply": False, "path": CONSTITUTION, "kind": "skip"}
    dest = repo / CONSTITUTION
    if dest.is_symlink() or (dest.exists() and not dest.is_file()):
        item.update(kind="conflict", reason=f"{CONSTITUTION} exists and is not a regular file; preserve it for review")
        return item
    if dest.exists() and dest.stat().st_nlink > 1:
        item.update(kind="conflict", reason=f"{CONSTITUTION} is a hardlink; refusing to write")
        return item
    if dest.is_file():
        item.update(kind="skip", reason="existing constitution preserved (user-owned content)")
        return item
    data = render_constitution(repo, strict_usage=False)
    _safe_dest(repo, CONSTITUTION)
    item.update(kind="write", reason="materialized constitution (missing on fresh install)", sha256=sha256_bytes(data))
    if apply:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)
        item["apply"] = True
    return item


def _zone_span(text: str) -> tuple[int, int, str]:
    """Locate (marker start, zone end, marker) for the first recognized marker."""

    positions = []
    for marker in MARKERS:
        index = text.find(marker)
        if index >= 0:
            positions.append((index, marker))
    if not positions:
        raise PHGovernanceError("constitution navigation marker missing; review existing principles first")
    start, marker = min(positions)
    heading = text.find(NAV_HEADING, start)
    if heading < 0:
        raise PHGovernanceError("navigation heading missing; review required")
    later = re.search(r"^#{1,2} ", text[heading + len(NAV_HEADING):], re.MULTILINE)
    end = heading + len(NAV_HEADING) + later.start() if later else len(text)
    return start, end, marker


def refresh_navigation(repo: Path, expected_sha: str, apply: bool) -> dict:
    """Replace only the navigation entries; principles and later sections stay."""

    path = _safe_dest(repo, CONSTITUTION)
    if not path.is_file():
        raise PHGovernanceError(f"missing {CONSTITUTION}")
    original = path.read_bytes()
    if not HEX64.fullmatch(expected_sha or ""):
        raise PHGovernanceError("--expected-sha must be the reviewed constitution's sha256")
    if sha256_bytes(original) != expected_sha:
        raise PHGovernanceError("constitution changed since review; refusing navigation replacement")
    text = original.decode("utf-8")
    start, end, _marker = _zone_span(text)
    rows = navigation_rows(repo, strict_usage=True)
    zone = text[start:end]
    matches = list(re.finditer(ENTRY_PATTERN, zone, re.MULTILINE))
    if matches:
        first = matches[0].start()
        prefix = zone[:first]
        suffix = re.sub(ENTRY_PATTERN, "", zone[first:], flags=re.MULTILINE)
        updated = text[:start] + prefix + "\n".join(rows) + "\n" + suffix + text[end:]
    else:
        if EMPTY_NAVIGATION not in zone:
            raise PHGovernanceError("unrecognized navigation entries; review required")
        updated = text[:start] + zone.replace(EMPTY_NAVIGATION, "\n".join(rows), 1) + text[end:]
    if apply:
        if path.read_bytes() != original:
            raise PHGovernanceError("constitution changed during navigation refresh")
        path.write_text(updated, encoding="utf-8")
    return {
        "action": "refresh-navigation",
        "ok": True,
        "apply": apply,
        "entries": len(rows),
        "sha256": sha256_bytes(updated.encode()),
    }


def check_governance(repo: Path) -> dict:
    """Read-only constitution integrity and legacy-layout checks."""

    problems: list[str] = []
    live = repo / CONSTITUTION
    if live.is_symlink() or not live.is_file():
        problems.append(f"missing regular file: {CONSTITUTION}")
    else:
        text = live.read_text(encoding="utf-8", errors="replace")
        for placeholder in UPSTREAM_PLACEHOLDERS:
            if placeholder in text:
                problems.append(f"{CONSTITUTION} still carries the upstream placeholder {placeholder}")
        if not any(marker in text for marker in MARKERS):
            problems.append(f"{CONSTITUTION} lost the PH-managed navigation zone")
        else:
            start, end, _marker = _zone_span(text)
            zone = text[start:end]
            indexed = {m.group(1) for m in re.finditer(r"^\- \[[^\]]+\]\(([^)]+)\)$", zone, re.MULTILINE)}
            try:
                expected = {
                    path.relative_to(repo / HOME).as_posix()
                    for path in ph_layout.constraint_entries(repo)
                }
            except ValueError as exc:
                problems.append(str(exc))
                expected = set()
            if indexed != expected:
                problems.append(
                    f"constitution navigation does not cover constraints exactly: "
                    f"missing={sorted(expected - indexed)[:5]} extra={sorted(indexed - expected)[:5]}"
                )
            for m in re.finditer(r"^\- \[[^\]]+\]\(([^)]+)\)$\n  使用时机：(.*)$", zone, re.MULTILINE):
                if not m.group(2).strip() or "待确认" in m.group(2):
                    problems.append(f"constitution entry {m.group(1)} has an empty usage line")
    for legacy in LEGACY_ROOTS:
        if (repo / legacy).exists():
            problems.append(f"{legacy}/ is the pre-1.2.1 layout; content must live under {HOME}")
    return {"action": "verify-governance", "ok": not problems, "problems": problems}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ph_governance.py")
    sub = parser.add_subparsers(dest="command", required=True)
    p_materialize = sub.add_parser(
        "materialize-constitution", help="create the materialized constitution when it is missing"
    )
    p_materialize.add_argument("--repo", required=True)
    p_materialize.add_argument("--apply", action="store_true")
    p_nav = sub.add_parser(
        "refresh-navigation", help="refresh reviewed live navigation without replacing principles"
    )
    p_nav.add_argument("--repo", required=True)
    p_nav.add_argument("--expected-sha", required=True)
    p_nav.add_argument("--apply", action="store_true")
    p_content = sub.add_parser("verify-content", help="verify project-specific constraints and evidence")
    p_content.add_argument("--repo", required=True)
    p_verify = sub.add_parser("verify", help="verify the materialized constitution navigation")
    p_verify.add_argument("--repo", required=True)
    args = parser.parse_args(argv)
    release_root = Path(__file__).resolve().parents[1]
    try:
        repo = find_repo(args.repo)
        if args.command == "materialize-constitution":
            payload = materialize_constitution(repo, args.apply)
        elif args.command == "refresh-navigation":
            payload = refresh_navigation(repo, args.expected_sha, args.apply)
        elif args.command == "verify-content":
            payload = ph_layout.verify_constraints(repo, release_root)
        else:
            payload = check_governance(repo)
    except (PHGovernanceError, ValueError, OSError) as exc:
        sys.stderr.write(f"error={exc}\n")
        return 2
    sys.stdout.write(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    # verify commands report problems in the payload AND through the exit code
    if args.command in {"verify", "verify-content"} and payload.get("ok") is False:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
